"""Initial Migration

Revision ID: 8637020c7fb3
Revises: 
Create Date: 2026-09-07 21:37:03.335606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8637020c7fb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome', sa.String(), nullable=False),
    sa.Column('Nome de usuário', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Telefone', sa.String(), nullable=False),
    sa.Column('Senha', sa.String(), nullable=False),
    sa.Column('Foto', sa.String(), nullable=True),
    sa.Column('Atividade', sa.Boolean(), nullable=True),
    sa.Column('Bio', sa.String(), nullable=True),
    sa.Column('Localização', sa.String(), nullable=False),
    sa.Column('Data', sa.String(), nullable=True),
    sa.Column('Equipamentos', sa.Enum('CANON', 'SONY', 'NIKON', 'FUJIFILM', name='equipamento'), nullable=False),
    sa.Column('Agencia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Nome de usuário')
    )
    op.create_table('portfolios',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID do Usuário', sa.Integer(), nullable=False),
    sa.Column('Título', sa.String(), nullable=False),
    sa.Column('Descrição', sa.String(), nullable=True),
    sa.Column('Classificação', sa.Enum('RETRATO', 'ESPORTIVA', 'CASAMENTO', 'EVENTOS', 'PRODUTOS', 'PAISAGEM', name='classificacao'), nullable=True),
    sa.Column('Foto Antes', sa.String(), nullable=True),
    sa.Column('Foto Depois', sa.String(), nullable=True),
    sa.Column('Compartilhado', sa.Boolean(), nullable=True),
    sa.Column('Atividade', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ID do Usuário'], ['usuarios.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
